// ─── Consent Wrapper Generator ────────────────────────────────────
//
// Generates framework-specific consent hooks/composables that
// the auto-fix engine can reference in its fix templates.

/**
 * Generate the full source code for a consent wrapper (hook/composable/script)
 * appropriate for the given framework.
 */
export function generateConsentWrapper(framework: string): string {
    switch (framework) {
        case 'react':
        case 'nextjs':
            return REACT_CONSENT_HOOK;
        case 'vue':
            return VUE_CONSENT_COMPOSABLE;
        default:
            return VANILLA_CONSENT_SCRIPT;
    }
}

/**
 * Return the import statement needed to use the consent hook for the given framework.
 */
export function getConsentImport(framework: string): string {
    switch (framework) {
        case 'react':
            return "import { useConsent } from '@/hooks/useConsent';";
        case 'nextjs':
            return "import { useConsent } from '@/hooks/useConsent';";
        case 'vue':
            return "import { useConsent } from '@/composables/useConsent';";
        default:
            return '';
    }
}

export function getConsentCheckExpression(framework: string, category: string): string {
    switch (framework) {
        case 'react':
        case 'nextjs':
            return `consentState?.${category}`;
        case 'vue':
            return `userConsent.${category}`;
        default:
            return `window.__etalon_consent?.${category}`;
    }
}

export function wrapInConsentCheck(
    code: string,
    framework: string,
    category: string,
): string {
    const check = getConsentCheckExpression(framework, category);

    switch (framework) {
        case 'react':
        case 'nextjs':
            return `{${check} && (\n  ${code}\n)}`;
        case 'vue':
            return code.replace(
                /^(<\w+)/,
                `$1 v-if="${check}"`,
            );
        default:
            return `if (${check}) {\n  ${code}\n}`;
    }
}

// ─── React Consent Hook ──────────────────────────────────────────

const REACT_CONSENT_HOOK = `// Auto-generated by ETALON
// Save this file to: src/hooks/useConsent.ts
//
// This hook manages user consent state for GDPR-compliant tracking.
// It persists consent choices in localStorage across sessions.

import { useState, useEffect, useCallback } from 'react';

interface ConsentState {
    analytics: boolean;
    marketing: boolean;
    functional: boolean;
}

const STORAGE_KEY = 'etalon-user-consent';

const DEFAULT_CONSENT: ConsentState = {
    analytics: false,
    marketing: false,
    functional: true,
};

export function useConsent() {
    const [consent, setConsentState] = useState<ConsentState>(DEFAULT_CONSENT);
    const [loaded, setLoaded] = useState(false);

    useEffect(() => {
        try {
            const stored = localStorage.getItem(STORAGE_KEY);
            if (stored) {
                setConsentState(JSON.parse(stored));
            }
        } catch {
            // localStorage unavailable
        }
        setLoaded(true);
    }, []);

    const setConsent = useCallback((type: keyof ConsentState, value: boolean) => {
        setConsentState(prev => {
            const next = { ...prev, [type]: value };
            try {
                localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
            } catch {
                // localStorage unavailable
            }
            return next;
        });
    }, []);

    const acceptAll = useCallback(() => {
        const all = { analytics: true, marketing: true, functional: true };
        setConsentState(all);
        try {
            localStorage.setItem(STORAGE_KEY, JSON.stringify(all));
        } catch {}
    }, []);

    const rejectAll = useCallback(() => {
        const none = { analytics: false, marketing: false, functional: true };
        setConsentState(none);
        try {
            localStorage.setItem(STORAGE_KEY, JSON.stringify(none));
        } catch {}
    }, []);

    return {
        consentState: consent,
        loaded,
        setConsent,
        acceptAll,
        rejectAll,
    };
}
`;

// ─── Vue Consent Composable ──────────────────────────────────────

const VUE_CONSENT_COMPOSABLE = `// Auto-generated by ETALON
// Save this file to: src/composables/useConsent.ts

import { ref, readonly, onMounted } from 'vue';

const STORAGE_KEY = 'etalon-user-consent';

const analytics = ref(false);
const marketing = ref(false);
const functional = ref(true);
const loaded = ref(false);

export function useConsent() {
    onMounted(() => {
        try {
            const stored = localStorage.getItem(STORAGE_KEY);
            if (stored) {
                const parsed = JSON.parse(stored);
                analytics.value = parsed.analytics ?? false;
                marketing.value = parsed.marketing ?? false;
                functional.value = parsed.functional ?? true;
            }
        } catch {}
        loaded.value = true;
    });

    const persist = () => {
        try {
            localStorage.setItem(STORAGE_KEY, JSON.stringify({
                analytics: analytics.value,
                marketing: marketing.value,
                functional: functional.value,
            }));
        } catch {}
    };

    const setConsent = (type: 'analytics' | 'marketing' | 'functional', value: boolean) => {
        if (type === 'analytics') analytics.value = value;
        if (type === 'marketing') marketing.value = value;
        if (type === 'functional') functional.value = value;
        persist();
    };

    const acceptAll = () => {
        analytics.value = true;
        marketing.value = true;
        functional.value = true;
        persist();
    };

    const rejectAll = () => {
        analytics.value = false;
        marketing.value = false;
        functional.value = true; // functional always on
        persist();
    };

    return {
        userConsent: readonly({ analytics, marketing, functional }),
        loaded: readonly(loaded),
        setConsent,
        acceptAll,
        rejectAll,
    };
}
`;

// ─── Vanilla JS Consent Script ───────────────────────────────────

const VANILLA_CONSENT_SCRIPT = `// Auto-generated by ETALON
// Add this script to your HTML before any tracker scripts.
//
// Usage:
//   if (window.__etalon_consent?.analytics) {
//     // Load analytics
//   }

(function() {
    var STORAGE_KEY = 'etalon-user-consent';
    var defaults = { analytics: false, marketing: false, functional: true };

    try {
        var stored = localStorage.getItem(STORAGE_KEY);
        window.__etalon_consent = stored ? JSON.parse(stored) : defaults;
    } catch(e) {
        window.__etalon_consent = defaults;
    }

    window.__etalon_setConsent = function(type, value) {
        window.__etalon_consent[type] = value;
        try {
            localStorage.setItem(STORAGE_KEY, JSON.stringify(window.__etalon_consent));
        } catch(e) {}
    };

    window.__etalon_acceptAll = function() {
        window.__etalon_consent = { analytics: true, marketing: true, functional: true };
        try {
            localStorage.setItem(STORAGE_KEY, JSON.stringify(window.__etalon_consent));
        } catch(e) {}
    };

    window.__etalon_rejectAll = function() {
        window.__etalon_consent = { analytics: false, marketing: false, functional: true };
        try {
            localStorage.setItem(STORAGE_KEY, JSON.stringify(window.__etalon_consent));
        } catch(e) {}
    };
})();
`;
